version: '3.8'
services:

  soapyserver:
    image: 'knegge/soapyremote-server:latest'
    build:
      context: .
    read_only: true
    network_mode: 'host'
    device_cgroup_rules:
      - 'c 189:* rwm'
    volumes:
      - '/var/run/dbus:/var/run/dbus'
      - '/var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket'
      - '/dev/bus/usb:/dev/bus/usb'

